### ISSUE TITLE
Claims and Mint module

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [aura-nw/aura#10]
Claims and Mint module serves a chain tokenomics. These two modules are present in almost all serious chains.

1. **Mint module**: mint module governs the flow of newly created token per block.

- Per 1000 token / block for example. How much goes to community pool, how much goes to staking, how much goes to artist incentives, should some be burned, ...
- This is an important module to govern the flow of token.

2. **Claims module**: free airdrop is just worst. Claims, however, is way better. It incentivies airdropped account to try-out the chain use cases.

![Screenshot from 2022-05-15 01-10-16](https://user-images.githubusercontent.com/23058164/168443633-5b86c9ee-a278-4be6-bd6d-6534a7f38aef.png)

**Comment by eledra89** [comment]
Thanks @nghuyenthevinh2000.

The Mint module is defined here: https://docs.aura.network/overview/protocol/mint
It is customized from legacy Cosmos Mint with a Max supply of 1 Billion tokens. That's it. The mint process is regulated by the inflation rate. We don't want to do anything fancy in minting.

I don't think we need Claim module at all. We don't do much airdrop like Stargaze or other full community oriented Cosmos Chain. Aura is an application oriented chain so that funds for airdrop can be taken from the eco-system growth fund and the logic can be implemented in CosWasm contract. You can take a look at the tokenomic secion in the Aura Whitepaper.

**Comment by nghuyenthevinh2000** [comment]
Smart Contract is not that all powerful. If the logic requires determining whether user has staked or not, it has to be in chain logic.
