### ISSUE TITLE
writing module to custom folder can lead to complexity in proto generation

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [aura-nw/aura#12]
By this point, I still don't understand why Aura decides to write custom module in custom folder. There is a specific reason why it is placed in x folder in the first place. 

Protobuf defines the datastructure of every cosmos module. When generating go files for protobuf, .pb.go files will be generated into x/module/types. By writing custom module to custom folder, it will complicate things such as making aura source incompatible with ignite cli. How so? 

- "ignite generate proto-go" for generating go files bases on protobuf will write to folder x
- "ignite scaffold module" for creating new custom module will also write to folder x

**Comment by eledra89** [comment]
We move it to custom folder because we write a wrap layer around the original module with some of the custom code. We follow Terra classic approach actually. It was never intended to work with ignite-cli in the first place. If it works out of the box then that's great. But if not, it is not that big of a deal. Basically:

x is for new modules that we write from scratch.
custom is for wrapped layer over old modules.

**Comment by nghuyenthevinh2000** [comment]
feel weird to me actually. By now, terra-money/core has complied to a standard Cosmos chain source code.
